### ISSUE TITLE
Feature Request D::BUS Integration

### ISSUE THREAD

**Issue by ianmarmour** [SteamDeckHomebrew/PluginLoader#1]
Just going to leave this idea here, if we're already running this plugin manager service in system-d we should hook it into D::BUS to allow for some IPC. I think we could probably provide this type of messaging by having some optional properties in the [JS Plugin Type](https://github.com/WerWolv/SteamOS-Plugin-Manager/blob/main/template_plugin.js) and managing the D::BUS calls/responses in the actual Rust code. I would be interested to hear your feedback, I'm working on the application side right now and having functionality like this would benefit quite a few projects.

The other outstanding thing noted here is it looks like plugins are limited to JS code, I wonder can we use native extensions/bindings by default (I would assume not?)

**Comment by Philip-Scott** [comment]
Commenting findings here: I had dbus working on a plugin after adding the following lines to the `[Service]` block on the `plugin_loader.service` file. We may be able to get away without the User and Group lines, I'll have to try more things tomorrow :) 

```
[Service]
User=deck
Group=deck
Environment=DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
...
```

Not sure if it was expected that this service was running as root btw

**Comment by WerWolv** [comment]
I think this can be closed now because you should easily be able to access dbus stuff from within python
