### ISSUE TITLE
Deck UI freezing with new version

### ISSUE THREAD

**Issue by LiamDawe** [SteamDeckHomebrew/PluginLoader#11]
Testing out the new version, it seems to detect plugins but when you go down to the Plugin menu and either click the A button or moving the Thumbstick right to select an option, the whole Deck UI freezes requiring a suspend and reload to get it working again.

Not really sure how to provide any logs on this one.

Testing with the music plugin: https://github.com/Philip-Scott/media-controls-plugin (since there's no demo plugin)

Edit: happens with no plugins installed too

**Comment by marios8543** [comment]
Physical controls are not supported currently. You can only navigate plugins with the touch screen

**Comment by WerWolv** [comment]
I don't think the UI freezes, it just focused an invalid element. You can simply use the touch screen to select something else again.

Focus is kind of an issue that we probably won't be able to do much about since it's all handled inside of steam

**Comment by LiamDawe** [comment]
I see, thanks for the insight there!
