### ISSUE TITLE
Seemingly randomly, the Plugins menu doesn't appear

### ISSUE THREAD

**Issue by LiamDawe** [SteamDeckHomebrew/PluginLoader#12]
I don't know what's causing it, but at random the Plugins menu just doesn't appear. 

Sometimes a Deck restart will make it appear but not always.

What can I do to help you figure out why this is happening?

**Comment by marios8543** [comment]
Does the icon on the quick access menu show up ? When does it happen ? Does it disappear randomly without exiting to desktop or anything?

**Comment by marios8543** [comment]
As for the restart not always making it re-appear, we already know there is a bug where the injector will run before steam has completely initialized which will make the loader crash. We're working towards fixing it.

**Comment by LiamDawe** [comment]
The icon does not appear no, that's what I mean, sorry should have said the specifically.

I replicated it just then by restarting, it showed up again, so i went to desktop mode, came back to Gaming Mode and the icon has vanished.

**Comment by marios8543** [comment]
Yes, the loader will not inject again if the steam client exits and re-opens. We're already aware this is a problem and will fix it soon.

**Comment by LiamDawe** [comment]
Ah awesome okay.

Sorry to keep reporting stuff you might already know, just want to be sure everything is covered as there will obviously be a lot of eyes on it and people trying to use it :)

**Comment by marios8543** [comment]
It's ok. It's good to get some feedback on what works and what doesn't, as well organize it in the GitHub issues, since we don't really add them ourselves :)
