### ISSUE TITLE
Can not leave plugin menu when focused

### ISSUE THREAD

**Issue by SpyrexDE** [SteamDeckHomebrew/PluginLoader#15]
Probably already known:
When the plugin menu is entered by pressing the "a"-button there is no way to get out of the menu, except using the touchscreen. When inside a plugin view ("main_view_html") even the touch screen method does not work and you have to toggle sleep mode off and on again.
Being able to press the "b"-button when a plugin view is opened to bring the user back to the plugin menu as well as being able to leave the plugin menu would be the optimal solution.

**Comment by marios8543** [comment]
When inside the main view, tapping on the "Plugins" title, will bring the plugin menu back.
Regarding the physical controls, it is already known that they don't work, and probably will not any time soon
https://github.com/SteamDeckHomebrew/PluginLoader/issues/11

**Comment by SpyrexDE** [comment]
> When inside the main view, tapping on the "Plugins" title, will bring the plugin menu back.

Maybe mention that in the readme or add a back button instead.

**Comment by marios8543** [comment]
Yep, this probably needs to be added to the readme
