### ISSUE TITLE
Add way for plugin views to stay loaded after going back to plugin page

### ISSUE THREAD

**Issue by SpyrexDE** [SteamDeckHomebrew/PluginLoader#16]
This would be helpful when for example javascript code is not fully executed yet or should work in the background.

**Comment by marios8543** [comment]
Well JavaScript is for the most part meant to accommodate the UI display logic. Btw now you can execute long-running python logic in the main method of your plugin. I don't know what your use-case is but maybe you can run your logic there and communicate with your plugin ?

**Comment by SpyrexDE** [comment]
I just tried to play music using the HTML video tag that obviously stops playing when the plugin view's location is changed. To prevent that, I would have to play the audio using python which is a bit more work than just with HTML.
But probably you are right and outsourcing these background tasks should be done by python.

**Comment by marios8543** [comment]
Well the way everything works now, it's not particularly easy to implement this, so I guess the approach should always be to keep long running logic outside of js.
