### ISSUE TITLE
Change title when inside plugin view

### ISSUE THREAD

**Issue by SpyrexDE** [SteamDeckHomebrew/PluginLoader#17]
Something like this would be more intuitive to understand when inside a plugin view:
<img src="https://user-images.githubusercontent.com/57133330/161622466-e2fdb394-5e81-4c95-9b6b-647db538ed78.png" height= 200></img>

**Comment by marios8543** [comment]
yea this looks good. i'll look into implementing it

**Comment by marios8543** [comment]
https://github.com/SteamDeckHomebrew/PluginLoader/commit/fe53bcf127cfe3775a4f2c9c9c53286054324b40
