### ISSUE TITLE
Cannot go back from selected plugin back to main plugin loader menu

### ISSUE THREAD

**Issue by TrainDoctor** [SteamDeckHomebrew/PluginLoader#23]
Title describes it all. I have to restart the entire device to be able to select a different plugin.
I'm going to assume that this is related to issues with html/js and the hard-coded steam controls.
I also can't enable sshd using the extra-settings plugin but that's not the focus of this issue.

**Comment by Philip-Scott** [comment]
It's not too intuitive, but it is working for me by tapping on the Plugins title at the top of the tab :)

**Comment by TrainDoctor** [comment]
> It's not too intuitive, but it is working for me by tapping on the Plugins title at the top of the tab :)

Well then I've got a different problem since I can't seem to find the plugins title thing. I'll try again in the morning, cheers.

**Comment by SpyrexDE** [comment]
The Extra-Settings plugin is currently not working due to missing root permissions. Just try some other plugins that don't need to run as root as for example my calculator plugin: https://github.com/SpyrexDE/SDH-Calculator
 And remember: As soon as the Plugins tab is focused you **have to** use the touchscreen.

**Comment by marios8543** [comment]
Duplicate of https://github.com/SteamDeckHomebrew/PluginLoader/issues/15
Also related to https://github.com/SteamDeckHomebrew/PluginLoader/issues/17 which is on the todo list

**Comment by marios8543** [comment]
https://github.com/SteamDeckHomebrew/PluginLoader/commit/fe53bcf127cfe3775a4f2c9c9c53286054324b40
