### ISSUE TITLE
Installation instructions ask user to use an external site

### ISSUE THREAD

**Issue by 5HT2** [SteamDeckHomebrew/PluginLoader#25]
I'm curious *why* this is being done. My best guess is it's for analytics / tracking reasons (which github provides to you already, though with a bit more privacy for the users).

I would recommend hosting the file in the git repo and replacing the command with a link to it, honestly.

**Comment by WerWolv** [comment]
The entire reason is to shorten the link really. It's my own site with a PHP script that simply looks like this:
```php
<?php

  $url = 'https://raw.githubusercontent.com/SteamDeckHomebrew/PluginLoader/main/dist/install_release.sh';    
  echo file_get_contents($url);

?>
```

There's zero tracking going on there. We'd actually probably have more tracking by simply accessing GitHub directly lol

**Comment by 5HT2** [comment]
Ah, I didn't realize `install_release.sh` was in this repo. `https://github.com/SteamDeckHomebrew/PluginLoader/raw/main/dist/install_release.sh` is still shorter (note it's using `raw` instead of `blob`).

It would probably be ideal to put it on a new line, for example:

6. Open a terminal and paste the following command into it:
`curl -L https://github.com/SteamDeckHomebrew/PluginLoader/raw/main/dist/install_release.sh | sh`

**Comment by TrainDoctor** [comment]
> Ah, I didn't realize `install_release.sh` was in this repo. `https://github.com/SteamDeckHomebrew/PluginLoader/raw/main/dist/install_release.sh` is still shorter (note it's using `raw` instead of `blob`).
> 
> It would probably be ideal to put it on a new line, for example:
> 
>     6. Open a terminal and paste the following command into it:
>        `curl -L https://github.com/SteamDeckHomebrew/PluginLoader/raw/main/dist/install_release.sh | sh`

Definitely agree with this sentiment. Better to link directly back to the repo. While I know Wolv is trustworthy I think users would have less questions if the install instructions pointed back to the same repo.
