### ISSUE TITLE
Exit with status code 1

### ISSUE THREAD

**Issue by heavyelement** [SteamDeckHomebrew/PluginLoader#3]
Once enabled, the systemd service exits at system startup with status=1/FAILURE and no further info.

If I manually start the service, it will say 
```
Started SteamDeck Plugin Manager:
  Available Content:
    MainMenu
    Toast
    data:text/html,&lt;body&gt;&lt;%2fbody&gt;
    QuickAccess
    data:text/html,&lt;body&gt;
    SP
{"id":1,"result":{"type":"undefined"}}}
plugin_manager.service: Deactivated successfully.
pid 6469 != 5676, skipping destruction (fork without exec?)
```

And when I open the QuickAccess menu, the system becomes completely unresponsive until I hold the power button to bring up the menu and then the QA menu goes away.

I don't have any plugins installed.

EDIT: After rebooting the device again and running `sudo systemctl status plugin_manager` I see the error:
```
× plugin_manager.service - SteamDeck Plugin Manager
     Loaded: loaded (/etc/systemd/system/plugin_manager.service; enabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Fri 2022-04-01 17:02:12 EDT; 3min 12s ago
    Process: 901 ExecStart=/home/deck/homebrew/services/plugin_manager/plugin_manager (code=exited, status=1/FAILURE)
   Main PID: 901 (code=exited, status=1/FAILURE)
        CPU: 4ms

Apr 01 17:02:12 steamdeck systemd[1]: Started SteamDeck Plugin Manager.
Apr 01 17:02:12 steamdeck plugin_manager[901]: Error: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }))
Apr 01 17:02:12 steamdeck systemd[1]: plugin_manager.service: Main process exited, code=exited, status=1/FAILURE
Apr 01 17:02:12 steamdeck systemd[1]: plugin_manager.service: Failed with result 'exit-code'.
```

I've also tried adding the template_plugin.js file to the plugin directory and once I enable the plugin manager I don't see it in the list and tapping "A" to enter the plugin manager list freezes the system.

**Comment by hashworks** [comment]
It seems that the service starts before the CEF remote debugging endpoint becomes available. It needs to wait on another service or try some time before exiting.

**Comment by marios8543** [comment]
Closing since the old version is no longer actively developed
