### ISSUE TITLE
How should external dependencies be handled for plugins? 

### ISSUE THREAD

**Issue by Philip-Scott** [SteamDeckHomebrew/PluginLoader#30]
Since the CI tool builds a python executable and that is what gets shipped, this file contains the dependencies required to run the Plugin Loader. However, it appears to be unable to read other external dependencies even if they are already installed to the Deck user using pip. 

```log
[loader][ERROR]: Could not load /home/deck/homebrew/plugins/music-plugin/main.py. No module named 'dbus'
```

This does not seem to be a systemd issue, as if systemd starts a bash script such as the following, the music plugin will load correctly.

```bash
#!/bin/bash
python3 /home/deck/PluginLoader/plugin_loader/main.py
```

**Comment by TrainDoctor** [comment]
With my plugin which will be focused on performance presets I've just added the needed library for VDF manipulation to a folder and am inserting it into the path at the start and calling it a day. Haven't tested if this will work yet but it's worth a try.

**Comment by TrainDoctor** [comment]
I believe that our eventual end goal of moving plugins towards being their own self-contained programs which will utilize tcp sockets to interact with Plugin Loader, for now dependency handling will be down to the plugin developers.

As a general rule, if the plugin can be compiled w/static linking for it's dependencies then that will be the recommended method.
If static linking is not possible and the Deck does not ship with the needed package manager/dependency resolution of choice on the developers end then they will need to handle that themselves. Usage of virtual environments for python dependencies is probably best for python in particular.
