### ISSUE TITLE
Which password?

### ISSUE THREAD

**Issue by emanresu2** [SteamDeckHomebrew/PluginLoader#36]
Which password does it want? I only ever set one password for "Steam Deck User" on this device and apparently it's not the one it wants. It also just gives me literally 5 seconds to type something in before it fails.

![Screenshot_20220413_175821](https://user-images.githubusercontent.com/28871543/163223146-ed3ec755-e595-4163-af64-390a6a738231.png)

**Comment by emanresu2** [comment]
Thanks for your reply.
Pretty sure I did set a password before as it was required for another thing I tried.
I set the password to "deck" but it's still not happy. So I assume my OS has an issue somewhere? 
![Screenshot_20220413_175821](https://user-images.githubusercontent.com/28871543/163246937-06095b2b-3161-4ffd-b1b4-7b8cbeae29bd.png)

**Comment by marios8543** [comment]
Try the same install command but with `sudo sh` instead of sh.

**Comment by marios8543** [comment]
ok nevermind the above, the release script was accidentally modified to accomodate a newer version which is not yet released. Try your original command again, this should not require root at all
