### ISSUE TITLE
Script for refetching all PluginLoadeplugins

### ISSUE THREAD

**Issue by isopix** [SteamDeckHomebrew/PluginLoader#42]
Hi,

I wrote it, because adding form interface doesn't worked few days ago for me. I think it can be useful for others:

#!/bin/sh
chmod -R 750 ~/homebrew 
cd ~/homebrew/plugins
for i in SteamDeckHomebrew/Mopidy-Controller SteamDeckHomebrew/ExtraSettingsPlugin SpyrexDE/SDH-BigPictureMode SpyrexDE/SDH-Calculator NegativeI0N/SDH-ClassicTheme SteamDeckHomebrew/ExtraSettingsPlugin NGnius/PowerTools suchmememanyskill/SDH-CssLoader; do
        echo "refetching: $i"
        rm -rf "$HOME/homebrew/plugins/`basename $i`"
        git clone --recursive "https://github.com/$i"
done

**Comment by marios8543** [comment]
Latest release should fix fetching from the store. Also there is a bug in the loader that breaks plugins with subfolders so you really shouldn't git clone into the plugin dir until that's fixed.
