### ISSUE TITLE
Plugin just disappeared

### ISSUE THREAD

**Issue by dragoonDorise** [SteamDeckHomebrew/PluginLoader#43]
Hi, was using the PowerTools plugin, it crashed the Performance Overlay and had to restart my Deck, now the plugin is gone, the files are on the homebrew folder but it's not showing up on the Plugins section. It just reads "No plugins installed"

**Comment by Outpox** [comment]
Happened to me once and this did the trick
```
sudo systemctl restart plugin_loader.service
```  
Although your restarted the  deck so that shouldn't be required. 🤔  
  
You can also try to ask on the dedicated discord.

**Comment by marios8543** [comment]
Try using the latest Release
