### ISSUE TITLE
Hot-reload, but files are also made read only, why?

### ISSUE THREAD

**Issue by MiraiSubject** [SteamDeckHomebrew/PluginLoader#44]
I might be misunderstanding the point of "hot reload", because my interpretation comes from Hot Module Replacement in Javascript, but why are the folder and files getting write disabled when the plugin loader starts?  

Currently I'm trying to use a remote VSCode instance on the steam deck while it's in gaming mode to create the plugin on my PC, and I keep running into permission errors while trying to make changes. I'm logged in as the `deck` user to make these changes.

![image](https://user-images.githubusercontent.com/803255/165148750-7ec49a94-9410-4dea-9870-05cc56472275.png)

What is the hot reload flag supposed to mean in the `config.json` of the plugin? 
``` 
"flags": [
   "_hot_reload",
]
```
https://github.com/SteamDeckHomebrew/PluginLoader/blob/73559ae8c7b1eba15340bbdde00d8b2b4b31f5ff/plugin_loader/main.py#L30-L32

**Comment by NGnius** [comment]
I'd imagine changing the permissions on startup is to prevent non-root users from replacing files, which would allow anyone to run arbitrary code with the permissions of your plugin (more of a concern for plugins with root permissions).

The best way to get around this write protection is to run as root, or symlink your plugin folder to a writable directory somewhere else on your Deck. Personally, I just `sftp` to load my code changes onto the Deck (to a folder which is symlinked to `~/homebrew/plugins/<my plugin>`); I can't be bothered to use Visual Studio.

The `hot_reload` flag was replaced by the `debug` a couple of releases ago, but they did/do effectively the same thing: check the plugin for file changes and then reload the whole plugin (notably: the python module for the plugin).

**Comment by marios8543** [comment]
^ Pretty much. Documentation is still shoddy, but we're working on it. But yes, `hot_reload` was replaced by `debug`, and the perm thing is there, so that non-root plugins can't edit their flags to become root. You can still edit the files with root permissions.

**Comment by MiraiSubject** [comment]
Alright, thanks for the explanations. I understand. 

Right now my solution is to do a dance of turn plugin off, make changes, enable plugin etc and that's good enough for me at the moment. I'll keep an eye out for the documentation!
