### ISSUE TITLE
Python backend on 127.0.0.1:1337 only serves text

### ISSUE THREAD

**Issue by MiraiSubject** [SteamDeckHomebrew/PluginLoader#45]
I have an image in my plugin folder which I'm trying to to show in Steam, however I found out that loading an image (or probably any non-text based asset) returns a 500 server error due to the backend trying to decode it as utf-8 text. 

Example:
`http://127.0.0.1:1337/plugins/plugin_resource/1650910504.3644676/image.jpg` returns 500 server error
`http://127.0.0.1:1337/plugins/plugin_resource/1650910504.3644676/main_view.html` shows the HTML page as text. 

The image is located in `~/homebrew/plugins/my_plugin/image.jpg` 

This is the error message I got from `journalctl`: 

```
Apr 25 21:11:34 steamdeck PluginLoader[33099]: [loader][INFO]: <module 'posixpath' from '/tmp/_MEI0WN3n2/posixpath.pyc'>
Apr 25 21:11:34 steamdeck PluginLoader[33099]: [web_protocol][ERROR]: Error handling request
Apr 25 21:11:34 steamdeck PluginLoader[33099]: Traceback (most recent call last):
Apr 25 21:11:34 steamdeck PluginLoader[33099]:   File "aiohttp/web_protocol.py", line 435, in _handle_request
Apr 25 21:11:34 steamdeck PluginLoader[33099]:   File "aiohttp/web_app.py", line 504, in _handle
Apr 25 21:11:34 steamdeck PluginLoader[33099]:   File "loader.py", line 152, in handle_sub_route
Apr 25 21:11:34 steamdeck PluginLoader[33099]:   File "codecs.py", line 322, in decode
Apr 25 21:11:34 steamdeck PluginLoader[33099]: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

The request I have is to allow the server to serve non-text based static assets.

**Comment by TrainDoctor** [comment]
This was only ever intended to serve text and upon discussion with team members, we have no plans to change this behavior as it is working as intended.
