### ISSUE TITLE
Uninstall instructions

### ISSUE THREAD

**Issue by ggppjj** [SteamDeckHomebrew/PluginLoader#46]
This plugin loader is really cool, and will likely get reinstalled at some point in the near future, but I'm looking to uninstall it while I wait out some of the more frustrating lockups that I've had with non-steam emulated games.

How would I uninstall the Plugin Loader from my Steam Deck, preferably without a reset?

Thanks!

**Comment by Outpox** [comment]
This was asked a few days ago on the Discord server, here's the answer given by @marios8543:
```
sudo rm -rf ~/homebrew
sudo systemctl disable --now plugin_loader.service
sudo rm /etc/systemd/system/plugin_loader.service
```

**Comment by ggppjj** [comment]
Thank you! Based on that, I've opened a pull request to add an uninstall script, #48. So this info is more readily available, I'd like to keep this issue open unless the pull request is accepted.
