### ISSUE TITLE
Triggering onload again

### ISSUE THREAD

**Issue by breadbakerman** [SteamDeckHomebrew/PluginLoader#47]
I am in the process of writing a small plugin that reads some infos and stats created by my own launcher script.
However, I noticed that when the plugin was activated and you close the side menu once you open it again later the displayed information is not updated.

I fixed that with a setTimeout but that just seems wrong. 
Is there a possibility to trigger the onload event again or is there even a better method I have overlooked?

**Comment by Outpox** [comment]
I've looked into it as well and from my understanding the quick menu page isn't unloaded, it's just hidden from the screen.  
This means that the `onload` event won't fire again unless you quit your custom menu to the plugin loader homepage and get back into it again.  
`setTimeout` is indeed not a solution to this issue (nor would be `setInterval`).

**Comment by marios8543** [comment]
You can try polling `document.hasFocus()` with setInterval. That sounds like what you want to do. Check out the injection code in plugin_page.js to see how we're using it and adapt it to your use-case.
