### ISSUE TITLE
Steam Deck Freezes whenever accessing the menu

### ISSUE THREAD

**Issue by baggyg** [SteamDeckHomebrew/PluginLoader#49]
Installed this via instructions including PowerTools. Whenever I access the menu the Steam Deck freezes and no commands work. I hold the power button to surpress the menu and then it works again. 

I would say this was PowerTools but also happened when PowerTools wasn't installed. 

Only odd thing about installation was that the Plugins folder was read only so I had to change the permissions. 

Any idea of what this could be? 

Thank you.

**Comment by marios8543** [comment]
Try the latest Release, and see if this fixes it for you.

**Comment by v-tron** [comment]
Latest release doesnt fix it. However, the Deck doesnt freeze, just the side menu does and normal controller input doesn't work, the touchscreen still work so you close the menu with the touch input and can then everything works again for some reason.

**Comment by NGnius** [comment]
Have you read the README, especially the section titled "Caveats"? Because what you're describing sounds awfully like someone who doesn't understand that you can only use the touchscreen to interact with plugins.

**Comment by v-tron** [comment]
Well that would certainly explain it lol
