### ISSUE TITLE
~/homebrew does not exist

### ISSUE THREAD

**Issue by SpyrexDE** [SteamDeckHomebrew/PluginLoader#5]
I followed this guide to install homebrew on my steamdeck: https://gist.github.com/uyjulian/105397c59e95f79f488297bb08c39146
However, I still have no ~/homebrew directory. I figured out that there is a linuxbrew directory but this one does not have a "service" folder.

**Comment by marios8543** [comment]
You probably got confused by the name, but that guide is unrelated to this project

**Comment by marios8543** [comment]
The included installation script manages that now.

**Comment by marios8543** [comment]
Also that guide is unrelated to this project.

**Comment by SpyrexDE** [comment]
Well, I hadn't seen the python-rewrite branch yet. Looks cool and works great. Keep up the good work :)

**Comment by marios8543** [comment]
thanks :)
