### ISSUE TITLE
All plugins running a root, regardless of `root` flag

### ISSUE THREAD

**Issue by Philip-Scott** [SteamDeckHomebrew/PluginLoader#52]
Even if the plugin.json file does not contain the "root" flag, the plugin seems to be loaded as root. I added the following to the top of the main.py file on a plugin without the root flag, 

```python
import os

f = open("/home/deck/media-controls-log", "a")
f.write(os.getenv("USER"))
f.close()
```

And the file contained `root`.

This seems to be the change which made  the daemon run as root at startup
https://github.com/SteamDeckHomebrew/PluginLoader/commit/7aa4e9106a57b95014bc93a01adf6085f4a5329f#diff-
That may be expected, if so maybe what is failing is starting the plugin as the "deck" user if the flag is not there within https://github.com/SteamDeckHomebrew/PluginLoader/blob/7d74e98f4f8a47daac85b5de1ef6aa29a1637c06/plugin_loader/main.py

**Comment by marios8543** [comment]
![image](https://user-images.githubusercontent.com/8387283/166247926-3df6b363-4e67-4a7d-a336-748a507de2b6.png)
