### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by mva94** [SteamDeckHomebrew/PluginLoader#59]
Hey can you please make a script for holoiso ?

[mva@mva ~]$ sudo curl -L https://github.com/SteamDeckHomebrew/PluginLoader/raw/main/dist/install_release.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1202  100  1202    0     0   2313      0 --:--:-- --:--:-- --:--:--  2313
Installing Steam Deck Plugin Loader release...
sudo: unknown user deck
sudo: error initializing audit plugin sudoers_audit
sudo: unknown user deck
sudo: error initializing audit plugin sudoers_audit
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Warning: Failed to create the file /home/deck/homebrew/services/PluginLoader: 
Warning: No such file or directory
  0 8482k    0   879    0     0   1242      0  1:56:33 --:--:--  1:56:33  1242
curl: (23) Failure writing output to destination
chmod: cannot access '/home/deck/homebrew/services/PluginLoader': No such file or directory
Created symlink /etc/systemd/system/multi-user.target.wants/plugin_loader.service → /etc/systemd/system/plugin_loader.service.
[mva@mva ~]$

**Comment by NGnius** [comment]
Does it work properly if you setup HoloISO with username `deck`?

**Comment by mva94** [comment]
Haven't tried that

**Comment by mva94** [comment]
Made it work , can you make a plugin to change tdp on ryzen 5800u ? Like tdp slider for the deck ?

**Comment by TrainDoctor** [comment]
This isn't really in the scope of HoloISO as holoiso is a desktop implementation and won't benefit from a lot of what these plugins do.

**Comment by pastaq** [comment]
#60 solves this.
