### ISSUE TITLE
Finding links to plugins and docs page

### ISSUE THREAD

**Issue by Dev-Filip** [SteamDeckHomebrew/PluginLoader#65]
Was wondering if these small changes could be done to improve navigability between the repo, community plugins listing and the plugin repos?
- Add a section in the GitHub repo readme that links to the list of community plugins and for the documentation page.
- Update the community plugins website to have direct links to the website/repo of the plugin so you can read the repos source and asses if you want to actually install this plugin. The names already include the GitHub author and the repo name, so adding a link would make sense.

**Comment by marios8543** [comment]
> will do

> will do
