### ISSUE TITLE
Link up the Plugin Store in the ReadMe?

### ISSUE THREAD

**Issue by xFaultx** [SteamDeckHomebrew/PluginLoader#77]
Title should be "Link to**"

It's a bit tedoous trying to find the plugin store when you're not directly on the steam deck, such as looking on your phone for the specific github page for a plugin. It would be a lot easier if there was a link in the ReadMe

**Comment by TrainDoctor** [comment]
I've addressed this in 4a2299f3ffa93f316641f19b855d02ff09d4f6cd for the react frontend update. If anything changes on the timeline for the react update, I'll manually add this change to the main branch if needed.

**Comment by xFaultx** [comment]
Ok awesome, thanks!
