### ISSUE TITLE
Wrong filename

### ISSUE THREAD

**Issue by LiamDawe** [SteamDeckHomebrew/PluginLoader#8]
Hi, your instructions say:

> Open a Terminal and type systemctl --now --user enable plugin_manager

But the file is named plugin_loader

I think the instructions definitely need some love.

> Place the executable under ~/homebrew/services/plugin_loader. Do not change the name of the file.

You don't say what executable?

There's also no step telling people to run the installer file, which needs sudo. To copy the service file over, it also needs sudo.

**Comment by WerWolv** [comment]
These instructions were for my old version of the plugin loader which has been completely rewritten and replaced with a new version. We'll update everything shortly.

**Comment by LiamDawe** [comment]
Okay, another issue WorkingDirectory in the .service file is missing an "=" on line 11.
