### ISSUE TITLE
Loader - Perpetual failure to inject Javascript bricks Steam Deck (?)

### ISSUE THREAD

**Issue by ryan-chau** [SteamDeckHomebrew/PluginLoader#86]
I was able to get the plugin loader installed, rebooted into gaming mode, and I successfully installed power tools and set lower GPU, etc. settings last night. However, I didn't try to turn on my deck again until this morning and it would just hang on a black screen. I tried the hard reset, going into bios and selecting the boot device (only the 1 SSD) but it wasn't until I plugged into an outlet that I was able to get something to run. Unfortunately, it was just the OS reimager.

I tried a few different things but basically I suspect that this error I saw somehow really messed something up on the backend. After running the curl command and entering my sudo password, I ran systemctl status plugin_loader and journalctl -xe to see the following error repeated every second: 
**PluginLoader93386]: [main][INFO]: Failed to inject JavaScript into tab.** 

I also saw this log on journalctl once in a while, but it may be unrelated: 
(yellow text) pipewire[1196]: spa.alsa: hw:acp5x,1: follower delay:576 target:256 thr:256, resync

I have gone through installing plugin loader multiple times this morning (3-4 reimages) testing out various things. I thought maybe it was because manually setting the wattage/GPU clock super low caused desktop mode to struggle. But the last time, I left everything on default and only did the following things: Login after reimage -> update SteamOS -> reboot -> developer mode and enable CEF remote debugging -> set hostname -> reboot -> desktop mode then switch to gaming mode -> desktop mode, set sudo, install script and check status/journalctl -> uninstall and switch to gaming mode. I have isolated it to this plugin as much as I could because I have been using the steam deck for about 4 days before I added the plugin loader and I had no issues until this morning. No bricking from the uninstall after install suggests that the install process is what bricks my steam deck. It could just be faulty hardware for me if nobody else is even seeing the failure in their logs. It just seems weird that it played nice with SteamOS enough for me to install the loader and the power tools plugin and then decided to brick.

**Comment by WerWolv** [comment]
`Failed to inject JavaScript into tab.` is normal. The plugin loader starts before steam is fully loaded and will try to start injecting itself into Steam. This will always fail a few times until Steam is fully loaded. The Plugin Loader will just retry until it manages to inject itself.

Does it happen too if you're just installing the plugin loader without installing Power Tools?

**Comment by NGnius** [comment]
This could be caused by enabling persistent mode in PowerTools and turning the GPU power all the way down. Generally, things boot & render very slowly when trying to use <0.1W of power

**Comment by ryan-chau** [comment]
> `Failed to inject JavaScript into tab.` is normal. The plugin loader starts before steam is fully loaded and will try to start injecting itself into Steam. This will always fail a few times until Steam is fully loaded. The Plugin Loader will just retry until it manages to inject itself.
> 
> Does it happen too if you're just installing the plugin loader without installing Power Tools?

Yes, this has happened every time, and I was never even able to reach the plugin GUI on the gaming mode side because manually rebooting and the desktop shortcut fail to get me to the gaming mode screen.



> This could be caused by enabling persistent mode in PowerTools and turning the GPU power all the way down. Generally, things boot & render very slowly when trying to use <0.1W of power

This is why I maxed out TDP and turned off GPU clock adjustments in my later trials. As a sanity check, I had those maxed but left the refresh rate/framerate to 40Hz and 20fps before running the curl and install script again about 20 minutes ago and the screen is still frozen when it tries to boot into gaming mode. Before I installed the plugin loader and power tools the first time, I had 0 trouble booting even with everything at the lowest settings with the standard Steam deck power options.

**Comment by ryan-chau** [comment]
Looks like the powertools plugin was still present on the desktop end. I thought it would be removed with pluginloader being uninstalled, but the homebrew/plugins folder is intact. Looks like this is just my error with janky settings on Power Tools.
