### ISSUE TITLE
PluginLoader makes audio glitch after wake

### ISSUE THREAD

**Issue by XargonWan** [SteamDeckHomebrew/PluginLoader#88]
PluginLoader is making games audio glitch after wake up.

Steps to reproduce:
- Install plugin loader
- Install some plugins (in my case: [SDH-AutoNightMode](https://github.com/LittleDonutG/SDH-AutoNightMode), [SDH-Bluetooth](https://github.com/Outpox/SDH-Bluetooth))
- Play a game
- Suspend the Steam Deck
- Wake it up
- The game is still playable but the sound is distorted

I completely uninstalled PluginLoader for now, and I didn't troubleshoot for the single plugins.

**Comment by TrainDoctor** [comment]
Unless you can prove that this is related to Plugin Loader, which does not in any way touch the audio of the Deck at all, then this issue is closed. Audio can be distorted when coming out of sleep normally on the Deck and this shouldn't be attributed to Plugin Loader.
