### ISSUE TITLE
Power tools keeps disappearing every time I restart the deck.

### ISSUE THREAD

**Issue by TheRealRws** [SteamDeckHomebrew/PluginLoader#99]
No matter if i install powertools with command line, plugin store or using emudeck it always disappears after I restart my deck. 

Updated plugin loader to the newest release and it still persists. Other plugins do stay.

**Comment by TheRealRws** [comment]
Seems its caused by the steam beta. Not the os but the actual launcher beta.

**Comment by TrainDoctor** [comment]
This sounds like an issue to report to the power tools developer NGnius.
